version: '3.7'

services:
    mariadb:
        build: ./requirements/mariaDB
        image: mariadb
        container_name: mariadb
        env_file:
            - .env
        ports:
            - "3306"
        volumes:
            - mdb-volume:/var/lib/mysql
        networks:
            - my-network
        restart: always


    wordpress:
        build: ./requirements/wordpress
        image: wordpress
        container_name: wordpress
        env_file:
            - .env
        ports:
            - "9000"
        volumes:
            - my-volume:/var/www/html
        depends_on:
            - nginx
            - mariadb
        networks:
            - my-network
        restart: always

    nginx:
        build: ./requirements/nginx
        image: nginx
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - my-volume:/var/www/html
        networks:
            - my-network
        restart: always

    website:
        build: ./requirements/bonus/website
        image: website
        container_name: website
        ports:
            - "1337:1337"
        volumes:
            - web-volume:/var/www/html
        networks:
            - my-network
        restart: always

    adminer:
        build: ./requirements/bonus/adminer
        image: adminer
        container_name: adminer
        ports:
            - "80:80"
        networks:
            - my-network
        restart: on-failure

    cAdviser:
        build: ./requirements/bonus/cadvisor
        image: cadvisor
        container_name: cadvisor
        restart: always
        ports:
        - 8080:8080
        volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro

volumes:
  mdb-volume:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/zait-sli/data/db
  my-volume:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/zait-sli/data/vl
  web-volume:
    driver_opts:
      type: 'none'
      o: bind
      device: /Users/zait-sli/data/website
networks:
    my-network:
