version: '3.7'

services:
    mariadb:
        build: ./mariaDB
        image: mariadb
        container_name: mariadb
        ports:
            - "3306:3306"
        volumes:
            - mdb-volume:/var/lib/mysql
        networks:
            - my-network
        restart: always


    wordpress:
        build: ./wordpress
        image: wordpress
        container_name: wordpress
        ports:
            - "9000:9000"
        volumes:
            - my-volume:/var/www/html
        depends_on:
            - nginx
            - mariadb
        networks:
            - my-network
        restart: always

    
    nginx:
        build: ./nginx
        image: nginx
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - my-volume:/var/www/html
        networks:
            - my-network
        restart: always
    
    adminer:
        build: ./adminer
        image: adminer
        container_name: adminer
        ports:
            - "80:80"
        networks:
            - my-network
        restart: on-failure

    cAdviser:
        build: ./cadvisor
        image: cadvisor
        container_name: cadvisor
        restart: always
        ports:
        - 8080:8080
        volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro

volumes:
  mdb-volume:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/kali/volumes/db
  my-volume:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/kali/volumes/vl

networks:
    my-network:
